#!/usr/bin/env python3
"""
isolation_forest_siem.py - Phase 2 ML detection layer

Final-year Cyber Security Major Project, Leeds City College.
Author: Yosif Karageorgiev (with AI-assisted development; see README).

This script implements the Phase 2 machine-learning detection layer for
the project "AWS SIEM Baseline vs AI - Comparative Study". It reads the
8,636-event dataset collected during Phase 1, builds behavioural features
over short time windows, and fits an Isolation Forest to flag anomalous
windows. Detection performance is reported alongside the Phase 1 rule-
based result of 57% (4 of 7 attacks) for direct comparison.

The same script supports two run modes:
  - Real data: pass an OpenSearch JSON export with --input
  - Synthetic data: omit --input to generate a labelled test dataset

Usage:
    python isolation_forest_siem.py --input phase1_export.json
"""

import argparse
import json
import os
import re
from datetime import datetime, timedelta

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")  # write figures to disk rather than open a window
import matplotlib.pyplot as plt
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
import joblib

# Fixed random seed so model results are reproducible across runs. Common
# convention in the ML literature; any integer would do.
RANDOM_STATE = 42
OUTDIR = "docs/phase2_ml_siem"

# IP address of my Kali attacker VM during the Phase 1 attack run.
# Used only to evaluate detection accuracy after scoring - never given
# to the model as an input feature, so detection has to be based on
# behaviour alone.
ATTACKER_IP = "192.168.56.103"

# The four Windows Security event IDs that carry the most authentication
# signal in this lab. Each maps to a known type of activity.
EID_FAILED = 4625      # An account failed to log on
EID_SUCCESS = 4624     # An account was successfully logged on
EID_LOCKOUT = 4740     # A user account was locked out
EID_PRIV = 4672        # Special privileges assigned to new logon

# Event 4703 ("token right adjusted") is generated by Fluent Bit's own
# service process every few seconds while it ships logs. In this lab it
# accounted for ~94% of all recorded events (8,155 of 8,636) and carries
# no source IP, so it is excluded as shipper noise. Other low-volume
# Windows audit events were retained even when small, because events
# such as 4688 (process creation) can carry legitimate security signal.
NOISE_EVENT_IDS = {4703}


# =============================================================================
# 1. DATA LOADING
# =============================================================================

def load_opensearch_export(path):
    """Read an OpenSearch JSON export and return a clean table of events.

    OpenSearch exports come in a few different shapes (a wrapped response,
    a flat list, or one JSON per line). This function handles all three so
    the same code works regardless of how the export was produced.

    For each event it extracts five fields the model later needs:
    timestamp, event_id, src_ip, user, logon_type. Because winlogbeat in
    this lab did not promote fields like IpAddress to top-level JSON keys,
    the function falls back to parsing them out of the Message text when
    they are not available directly.
    """
    rows = []
    with open(path, "r", encoding="utf-8") as fh:
        text = fh.read().strip()

    # Detect the shape of the export and produce a flat list of event docs.
    docs = []
    try:
        obj = json.loads(text)
        if isinstance(obj, dict) and "hits" in obj:
            docs = [h.get("_source", h) for h in obj["hits"]["hits"]]
        elif isinstance(obj, list):
            docs = obj
        else:
            docs = [obj]
    except json.JSONDecodeError:
        # Fall back to newline-delimited JSON
        for line in text.splitlines():
            line = line.strip()
            if not line:
                continue
            d = json.loads(line)
            docs.append(d.get("_source", d))

    for d in docs:
        # Extract source IP, account name and logon type. Each falls back
        # to parsing the Message text when the field is not promoted.
        msg = d.get("Message", "") or ""

        ip = _first(d, ["src_ip", "source_ip", "IpAddress",
                        "winlog.event_data.IpAddress", "SourceIp"])
        if not ip:
            ip = _parse_msg(msg, ["Source Network Address", "Network Address",
                                  "Client Address"])

        user = _first(d, ["user", "TargetUserName", "AccountName",
                          "winlog.event_data.TargetUserName"])
        if not user:
            user = _parse_msg(msg, ["Account Name"])

        ltype = _to_int(_first(d, ["logon_type", "LogonType",
                                   "winlog.event_data.LogonType"]))
        if ltype is None:
            ltype = _to_int(_parse_msg(msg, ["Logon Type"]))

        rows.append({
            "timestamp": _first(d, ["@timestamp", "timestamp", "TimeCreated",
                                    "EventTime"]),
            "event_id": _to_int(_first(d, ["event_id", "EventID",
                                           "winlog.event_id", "EventCode"])),
            "src_ip": ip,
            "user": user,
            "logon_type": ltype,
        })

    df = pd.DataFrame(rows)
    df["timestamp"] = pd.to_datetime(df["timestamp"], errors="coerce", utc=True)
    df = df.dropna(subset=["timestamp"])
    return df


def _first(d, keys):
    """Look through a list of possible field names and return whichever
    one is actually present in the data. Different log shippers store
    the same information under different keys, so trying several names
    makes the loader portable. Dotted keys like 'winlog.event_data.IpAddress'
    are followed into nested sub-dictionaries.
    """
    for k in keys:
        if k in d and d[k] not in (None, ""):
            return d[k]
        if "." in k:  # nested-path lookup
            cur, ok = d, True
            for part in k.split("."):
                if isinstance(cur, dict) and part in cur:
                    cur = cur[part]
                else:
                    ok = False
                    break
            if ok and cur not in (None, ""):
                return cur
    return None


def _parse_msg(msg, labels):
    """Extract a field value from the Windows event Message text.

    In this lab the OpenSearch index stored each event's Message as a
    single string, with key information like the source IP and username
    embedded inside it rather than promoted to JSON fields. This helper
    runs a regex over the Message text to pull out the value on the same
    line as a given label. Empty placeholders ('-') are skipped.
    """
    for label in labels:
        m = re.search(rf"{re.escape(label)}\s*:\s*([^\r\n]+)", msg)
        if m:
            val = m.group(1).strip()
            if val and val != "-":
                return val
    return None


def _to_int(v):
    """Safely cast a value to int. Returns None for missing or non-numeric
    inputs rather than raising, so the rest of the pipeline can carry on."""
    try:
        return int(v)
    except (TypeError, ValueError):
        return None


# =============================================================================
# 1b. SYNTHETIC DATA GENERATOR (testing only)
# =============================================================================

def make_synthetic():
    """Generate a labelled test dataset that reproduces the Phase 1 totals:
    28x4625, 7x4624, 1x4740, 6x4672 plus benign noise. Each attack is tagged
    so the evaluation step can measure per-attack detection. Used only to
    sanity-check the pipeline; the real evaluation uses load_opensearch_export.
    """
    rng = np.random.default_rng(RANDOM_STATE)
    base = datetime(2026, 5, 20, 9, 0, 0)
    rows = []

    def add(ts, eid, src, user, ltype, attack):
        rows.append({"timestamp": ts, "event_id": eid, "src_ip": src,
                     "user": user, "logon_type": ltype, "attack": attack})

    benign_ips = [f"192.168.56.{n}" for n in (20, 21, 22, 23, 50, 51)]
    n_benign = 8636 - (28 + 7 + 1 + 6)
    for _ in range(n_benign):
        ts = base + timedelta(seconds=int(rng.integers(0, 8 * 3600)))
        eid = int(rng.choice([EID_SUCCESS, EID_PRIV, 4634, 4648],
                              p=[0.45, 0.10, 0.40, 0.05]))
        add(ts, eid, rng.choice(benign_ips),
            rng.choice(["alice", "bob", "svc_backup"]),
            int(rng.choice([2, 3, 5])), "benign")

    # Attack 2 - SMB brute force
    t = base + timedelta(hours=1)
    for i in range(20):
        add(t + timedelta(seconds=i * 2), EID_FAILED, ATTACKER_IP,
            "Administrator", 3, "A2_smb_bruteforce")

    # Attack 3 - authenticated login
    t = base + timedelta(hours=1, minutes=2)
    for i in range(6):
        add(t + timedelta(seconds=i), EID_SUCCESS, ATTACKER_IP,
            "Administrator", 3, "A3_auth_login")
        add(t + timedelta(seconds=i), EID_PRIV, ATTACKER_IP,
            "Administrator", 3, "A3_auth_login")

    # Attack 6 - RDP brute force
    t = base + timedelta(hours=1, minutes=10)
    for i in range(5):
        add(t + timedelta(seconds=i * 3), EID_FAILED, ATTACKER_IP,
            "Administrator", 10, "A6_rdp_bruteforce")

    # Attack 7 - WinRM brute force (with lockout)
    t = base + timedelta(hours=1, minutes=20)
    for i in range(3):
        add(t + timedelta(seconds=i * 4), EID_FAILED, ATTACKER_IP,
            "Administrator", 3, "A7_winrm_bruteforce")
    add(t + timedelta(seconds=20), EID_LOCKOUT, ATTACKER_IP,
        "Administrator", 0, "A7_winrm_bruteforce")
    add(t + timedelta(seconds=30), EID_SUCCESS, ATTACKER_IP,
        "Administrator", 3, "A7_winrm_bruteforce")

    # Attacks 1, 4, 5 - recon / enum / vuln scan. These are the rule-based
    # misses: very few events, mostly anonymous logon attempts.
    t = base + timedelta(minutes=30)
    add(t, EID_FAILED, ATTACKER_IP, "ANONYMOUS LOGON", 3, "A1_nmap_recon")
    t = base + timedelta(minutes=45)
    for i in range(2):
        add(t + timedelta(seconds=i), EID_FAILED, ATTACKER_IP,
            "ANONYMOUS LOGON", 3, "A4_smb_enum")
    t = base + timedelta(minutes=55)
    add(t, EID_FAILED, ATTACKER_IP, "ANONYMOUS LOGON", 3, "A5_ms17_010")

    df = pd.DataFrame(rows)
    df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True)
    return df


# =============================================================================
# 2. FEATURE ENGINEERING
# =============================================================================

def build_features(df, window="2min"):
    """Convert raw events into behavioural feature rows for the model.

    The detection approach is not to look at individual events but at
    summaries of behaviour. Events are grouped by source IP and into
    fixed time windows, and for each (IP, window) pair ten numeric
    features describe what happened: counts of failed and successful
    logons, lockouts and privilege events; the number of distinct usernames
    targeted; the ratio of failures to total activity; the ratios of
    anonymous and RDP logons; and the Shannon entropy of the event-ID
    mix as a measure of how varied the activity was.

    The model is only ever given these ten numeric features. It does not
    see the source IP, the attack label, or the raw event text. That
    means detection has to be based on behavioural pattern alone, which
    is the property that makes the result methodologically meaningful.
    """
    # Track whether the input data carried per-event attack labels.
    # Drives the evaluation logic later: with labels we measure per-attack
    # detection; without, we use source IP as ground truth.
    if "attack" not in df.columns:
        df = df.assign(attack="unknown")
        was_unlabelled = True
    else:
        was_unlabelled = False
    df = df.copy()

    # Drop log-shipper noise (Event 4703 in this lab).
    df = df[~df["event_id"].isin(NOISE_EVENT_IDS)]

    # Many Windows audit events have no source IP (local/system events).
    # Bucket them under 'localhost' so they still form feature windows;
    # remote activity stays grouped under its actual IP.
    df["src_ip"] = df["src_ip"].fillna("localhost")

    # Floor each timestamp to the nearest window boundary.
    df["bucket"] = df["timestamp"].dt.floor(window)

    feats = []
    for (ip, bucket), g in df.groupby(["src_ip", "bucket"]):
        eid = g["event_id"]
        total = len(g)
        failed = int((eid == EID_FAILED).sum())
        success = int((eid == EID_SUCCESS).sum())
        lockout = int((eid == EID_LOCKOUT).sum())
        priv = int((eid == EID_PRIV).sum())
        users = g["user"].dropna()
        anon = int((users.astype(str).str.upper() == "ANONYMOUS LOGON").sum())
        remote = int((g["logon_type"] == 10).sum())

        # Shannon entropy of the event-ID distribution in this window.
        # 0.0 = all the same type; higher = more varied mix.
        counts = eid.value_counts(normalize=True)
        entropy = float(-(counts * np.log2(counts)).sum()) if len(counts) else 0.0

        # Ground-truth attack label for this window. Used in evaluation,
        # never fed to the model.
        labels = set(g["attack"]) - {"benign", "unknown"}
        attack_label = sorted(labels)[0] if labels else "benign"

        feats.append({
            "src_ip": ip, "window": bucket, "total_events": total,
            "failed_logons": failed, "success_logons": success,
            "lockouts": lockout, "priv_events": priv,
            "distinct_users": int(users.nunique()),
            "fail_ratio": failed / total if total else 0.0,
            "anon_ratio": anon / total if total else 0.0,
            "remote_ratio": remote / total if total else 0.0,
            "event_id_entropy": entropy,
            "_attack": attack_label,
        })

    out = pd.DataFrame(feats)
    out.attrs["was_unlabelled"] = was_unlabelled
    return out


# Names of the ten numeric features the model is given. Bookkeeping
# columns (src_ip, window, _attack) are deliberately excluded so the
# model has to detect on behaviour alone.
FEATURE_COLS = ["total_events", "failed_logons", "success_logons", "lockouts",
                "priv_events", "distinct_users", "fail_ratio", "anon_ratio",
                "remote_ratio", "event_id_entropy"]


# =============================================================================
# 3. TRAIN, SCORE, EVALUATE
# =============================================================================

def run(df):
    """Fit the Isolation Forest, score every window, and report results."""
    os.makedirs(OUTDIR, exist_ok=True)
    feats = build_features(df)
    X = feats[FEATURE_COLS].to_numpy()

    # Standardise so no feature dominates because of its scale.
    # Failed-logon counts can reach into the hundreds while ratios sit
    # between 0 and 1; without scaling the counts would drown the ratios.
    scaler = StandardScaler()
    Xs = scaler.fit_transform(X)

    # Contamination tells the model what fraction of windows to expect
    # as anomalies. 0.05 is a starting point taken from the anomaly-
    # detection literature; a fuller study would sweep this value and
    # plot the resulting precision-recall trade-off.
    contamination = 0.05
    model = IsolationForest(
        n_estimators=200,           # 200 trees for stable scoring
        contamination=contamination,
        random_state=RANDOM_STATE,  # deterministic results across runs
    )
    model.fit(Xs)

    # score_samples returns higher numbers for more normal points
    # (long isolation paths). Negating it gives the more intuitive
    # 'higher = more anomalous' for the output CSV and figures.
    feats["anomaly_score"] = -model.score_samples(Xs)
    feats["flagged"] = model.predict(Xs) == -1

    # ---- Evaluation -----------------------------------------------------
    # Two scenarios:
    #   1. Synthetic data: every event has an _attack label, so we can
    #      measure 'how many distinct attacks did ML surface'.
    #   2. Real data: events are not individually labelled, but we know
    #      everything from the Kali attacker IP during the run was
    #      malicious. We measure recall on attacker windows and false
    #      positives on non-attacker windows.
    synthetic_mode = not feats.attrs.get("was_unlabelled", True)

    # Defaults for variables referenced later
    precision = recall = f1 = 0.0
    true_pos = false_neg = 0
    detected = all_attacks = missed = []
    attack_windows = feats.iloc[0:0]  # empty default
    benign_windows = feats.iloc[0:0]

    if synthetic_mode:
        attack_windows = feats[feats["_attack"] != "benign"]
        detected = sorted(attack_windows.loc[attack_windows["flagged"],
                                              "_attack"].unique())
        all_attacks = sorted(feats.loc[feats["_attack"] != "benign",
                                        "_attack"].unique())
        missed = [a for a in all_attacks if a not in detected]
        benign = feats[feats["_attack"] == "benign"]
        fp = int(benign["flagged"].sum())
        fp_rate = fp / len(benign) if len(benign) else 0.0
        ml_rate = (len(detected) / len(all_attacks) * 100) if all_attacks else 0.0
        # Approximate precision/recall/F1 from window-level results
        true_pos = int(attack_windows["flagged"].sum())
        recall = true_pos / max(len(attack_windows), 1)
        precision = true_pos / max(true_pos + fp, 1)
        f1 = (2 * precision * recall / (precision + recall)
              if (precision + recall) else 0.0)
    else:
        # Real-data ground truth: an attacker window is any feature row
        # whose source IP matches the known Kali address.
        attack_windows = feats[feats["src_ip"] == ATTACKER_IP]
        benign_windows = feats[feats["src_ip"] != ATTACKER_IP]
        true_pos = int(attack_windows["flagged"].sum())
        false_neg = int((~attack_windows["flagged"]).sum())
        fp = int(benign_windows["flagged"].sum())
        true_neg = len(benign_windows) - fp
        fp_rate = fp / len(benign_windows) if len(benign_windows) else 0.0
        ml_rate = (true_pos / len(attack_windows) * 100) if len(attack_windows) else 0.0
        recall = ml_rate / 100
        precision = true_pos / (true_pos + fp) if (true_pos + fp) else 0.0
        f1 = (2 * precision * recall / (precision + recall)
              if (precision + recall) else 0.0)

    # ---- Console report -------------------------------------------------
    # The output below is the primary terminal evidence for Phase 2. It is
    # also written to a text file and to the scored CSV, so it survives
    # closing the terminal.
    lines = []
    lines.append("=" * 60)
    lines.append("PHASE 2 - ISOLATION FOREST RESULTS")
    lines.append("=" * 60)
    lines.append(f"Mode                     : {'synthetic' if synthetic_mode else 'real data'}")
    lines.append(f"Raw events processed     : {len(df):,}")
    lines.append(f"Feature windows built    : {len(feats):,}  (2min buckets)")
    lines.append(f"Contamination setting    : {contamination}")
    lines.append(f"Windows flagged anomalous: {int(feats['flagged'].sum())}")
    lines.append("-" * 60)
    if synthetic_mode:
        lines.append(f"Distinct attacks present : {len(all_attacks)}")
        lines.append(f"Attacks ML detected      : {len(detected)}  -> {detected}")
        lines.append(f"Attacks ML missed        : {len(missed)}  -> {missed}")
        lines.append(f"ML detection rate        : {ml_rate:.0f}%")
    else:
        lines.append(f"Attacker IP              : {ATTACKER_IP}")
        lines.append(f"Attacker windows (truth) : {len(attack_windows)}")
        lines.append(f"Benign windows           : {len(benign_windows)}")
        lines.append(f"True positives           : {true_pos}")
        lines.append(f"False negatives          : {false_neg}")
        lines.append(f"False positives          : {fp}")
        lines.append(f"True negatives           : {len(benign_windows) - fp}")
        lines.append(f"Recall                   : {ml_rate:.0f}%")
        lines.append(f"Precision                : {precision:.2%}")
        lines.append(f"F1-score                 : {f1:.2f}")
        lines.append(f"False positive rate      : {fp_rate:.2%}")
    if synthetic_mode:
        lines.append(f"False positives (benign) : {fp}  ({fp_rate:.2%})")
        lines.append(f"Precision                : {precision:.2%}")
        lines.append(f"F1-score                 : {f1:.2f}")
    lines.append("-" * 60)
    lines.append("Phase 1 (rule-based) rate: 57%  (4/7)")
    if synthetic_mode:
        lines.append(f"Phase 2 (ML) rate        : {ml_rate:.0f}%  "
                     f"({len(detected)}/{len(all_attacks)})")
    else:
        lines.append(f"Phase 2 (ML) recall      : {ml_rate:.0f}%")
    lines.append("=" * 60)

    report = "\n".join(lines)
    print("\n" + report)

    # ---- Persist artefacts ---------------------------------------------
    # Three files (plus two figures) are written to docs/phase2_ml_siem/:
    #   - phase2_scored_windows.csv: every feature window with its anomaly
    #     score, sorted highest first. Opens in Excel for the Results
    #     chapter and forms the primary tabular evidence.
    #   - isolation_forest_model.joblib: the fitted model + scaler, saved
    #     so the same model can be reloaded later without retraining.
    #   - phase2_report.txt: text copy of the console summary.
    scored_path = os.path.join(OUTDIR, "phase2_scored_windows.csv")
    feats.sort_values("anomaly_score", ascending=False).to_csv(scored_path,
                                                                 index=False)
    joblib.dump({"model": model, "scaler": scaler, "features": FEATURE_COLS},
                os.path.join(OUTDIR, "isolation_forest_model.joblib"))
    with open(os.path.join(OUTDIR, "phase2_report.txt"), "w",
              encoding="utf-8") as fh:
        fh.write(report + "\n")

    _plot_scores(feats)
    _plot_comparison(detected, all_attacks, ml_rate, synthetic_mode)
    print(f"\nArtefacts written to: {OUTDIR}/")
    return feats


# =============================================================================
# 4. FIGURES
# =============================================================================

def _plot_scores(feats):
    """Histogram showing how the model's anomaly scores are distributed
    across benign and attacker windows. A well-performing model should
    show the two populations clearly separated, with attacker windows
    sitting at higher scores than benign windows. Heavy overlap would
    indicate the model is not distinguishing the two effectively.
    """
    fig, ax = plt.subplots(figsize=(9, 5))

    # Pick the right ground-truth mask: labelled attacks if present,
    # otherwise attacker IP for the real-data run.
    if (feats["_attack"] != "benign").any():
        attack_mask = feats["_attack"] != "benign"
    else:
        attack_mask = feats["src_ip"] == ATTACKER_IP

    benign = feats[~attack_mask]["anomaly_score"]
    attack = feats[attack_mask]["anomaly_score"]
    ax.hist(benign, bins=40, alpha=0.7, label="Benign windows")
    ax.hist(attack, bins=40, alpha=0.9, label="Attacker windows")
    ax.set_xlabel("Anomaly score (higher = more anomalous)")
    ax.set_ylabel("Number of windows")
    ax.set_title("Isolation Forest anomaly score distribution")
    ax.legend()
    fig.tight_layout()
    fig.savefig(os.path.join(OUTDIR, "fig_anomaly_scores.png"), dpi=150)
    plt.close(fig)


def _plot_comparison(detected, all_attacks, ml_rate, synthetic_mode):
    """Side-by-side bar chart of Phase 1 (rule-based) vs Phase 2 (ML)
    detection rate. The Phase 1 figure of 57% is fixed from the Phase 1
    results section; the Phase 2 figure is computed live from the current
    model run.
    """
    fig, ax = plt.subplots(figsize=(7, 5))
    phase1 = 4 / 7 * 100
    if synthetic_mode:
        phase2 = (len(detected) / len(all_attacks) * 100) if all_attacks else 0.0
    else:
        phase2 = ml_rate
    bars = ax.bar(["Phase 1\n(traditional SIEM)", "Phase 2\n(ML-enhanced)"],
                  [phase1, phase2], color=["#888888", "#2a7de1"])
    ax.set_ylabel("Detection rate (%)")
    ax.set_ylim(0, 110)
    ax.set_title("Detection rate: traditional vs ML-enhanced SIEM")
    for b, v in zip(bars, [phase1, phase2]):
        ypos = v - 6 if v > 95 else v + 2
        color = "white" if v > 95 else "black"
        ax.text(b.get_x() + b.get_width() / 2, ypos, f"{v:.0f}%",
                ha="center", color=color, fontweight="bold")
    fig.tight_layout()
    fig.savefig(os.path.join(OUTDIR, "fig_detection_comparison.png"), dpi=150)
    plt.close(fig)


# =============================================================================
# 5. ENTRY POINT
# =============================================================================

def main():
    ap = argparse.ArgumentParser(description="Phase 2 Isolation Forest SIEM model")
    ap.add_argument("--input", help="OpenSearch export (JSON/NDJSON). "
                                    "Omit to use built-in synthetic data.")
    args = ap.parse_args()

    if args.input:
        print(f"[*] Loading real data from {args.input}")
        df = load_opensearch_export(args.input)
    else:
        print("[*] No --input given; generating synthetic Phase 1-matched data.")
        df = make_synthetic()
    run(df)


if __name__ == "__main__":
    main()
