[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info

[INPUT]
    Name         winlog
    Channels     Application,Security,System
    Interval_Sec 1

[OUTPUT]
    Name            opensearch
    Match           *
    Host            192.168.56.1
    Port            9200
    Index           winlogbeat
    Suppress_Type_Name On
    tls             Off
